CREATE DATABASE ssm_04;
-- 创建图书表
CREATE TABLE book(
   `bid` INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    bname VARCHAR(255) DEFAULT NULL COMMENT '图书名称',
    bAuthor VARCHAR(255) DEFAULT NULL COMMENT '图书作者',
    bPubdate DATE DEFAULT NULL COMMENT '出版日期',
    bPrice DOUBLE DEFAULT NULL COMMENT '价格',
    bPublisher VARCHAR(255) DEFAULT NULL COMMENT '出版社',
    bDetail VARCHAR(255) DEFAULT NULL COMMENT '详情'
);